function restfull() {
    var sources = {
        shoes: {
            getAll: function (source) {
                for (var i = 0; i < shoeSource.length; i++) {
                    source.push(shoeSource[i]);
                }
            },
            getById: function (productId) {
                for (var i = 0; i < shoeSource.length; i++) {
                    if (shoeSource[i].Id == productId) {
                        return shoeSource[i];
                    }
                }
            },
        }
    };

    return sources;
};


var shoeSource =
    [
    { Id: 1, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/1.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
      { Id: 2, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/2.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
      { Id: 3, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/3.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
      { Id: 4, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/4.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
    { Id: 5, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/5.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
    { Id: 6, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/6.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
     { Id: 7, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/7.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
                { Id: 8, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/8.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' },
                    { Id: 9, Name: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit', Path: '/images/9.jpg', Description: 'Aenean condimentum, enim vel sagittis aliquet, nibh dolor pellentesque tellus, nec scelerisque ex felis ac lacus. Integer quis ante quam. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus eleifend auctor ornare. Donec blandit euismod sem, sit amet venenatis urna elementum non. Proin vulputate bibendum sollicitudin. Praesent in massa nec elit porttitor facilisis eu vitae mauris. Curabitur blandit lacinia consequat. Donec tortor purus, volutpat vel sollicitudin vitae, pulvinar ut dui. Fusce mollis orci sed ex elementum, sit amet aliquam mauris varius. Sed laoreet turpis sit amet nunc elementum, ut commodo neque ultrices. Etiam eu tincidunt risus. Quisque in sem eleifend, gravida lectus rhoncus, dictum quam. Aliquam eget pretium dolor, fringilla posuere risus.' }
    ];